image: docker

services:
  - docker:bind

stages:
  - develop

develop:
  stage: develop
  only:
    - develop
  script:
    - docker-compose -f docker-compose.stage.yml down
    - cp .env.stage .env
    - docker-compose -f docker-compose.stage.yml up --build -d
    - docker-compose -f docker-compose.stage.yml exec -T php composer install
    - docker-compose -f docker-compose.stage.yml exec -T php php artisan migrate --seed
    - docker-compose -f docker-compose.stage.yml exec -T php php artisan key:generate
    - docker-compose -f docker-compose.stage.yml exec -T php php artisan optimize
    - docker-compose -f docker-compose.stage.yml exec -T php php artisan config:clear

    - docker-compose -f docker-compose.stage.yml exec -T php php artisan migrate:refresh --step=2

