version: '3'
services:

  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./Dockerfile/Dockerfile
    container_name: time-api-php
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/php.ini:/usr/local/etc/php/php.ini
      - vendor:/var/www/vendor
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    networks:
      - time-api-net

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: time-api-nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - php
      - db
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-web
      - traefik.http.routers.time-api.rule=Host(`time-api.selectedstartups.com`)
      - traefik.http.routers.time-api.service=nginx-time-api
      - traefik.http.routers.time-api.priority=10
      - traefik.http.routers.time-api.entrypoints=https
      - traefik.http.middlewares.time-api.redirectscheme.scheme=https
      - traefik.http.middlewares.time-api.redirectscheme.permanent=true
      - traefik.http.routers.time-api.tls.certresolver=myresolver
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - time-api-net
      - traefik-web

  #MySQL Service
  db:
    image: mysql:latest
    container_name: time-api-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: times_db
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3366:3306"
    networks:
      - time-api-net

#Docker Networks
networks:
  time-api-net:
  traefik-web:
    external: true

#Volumes
volumes:
  dbdata:
  vendor:
